<?php
$z[0]=Array("global","",369,398);
$z[0][4]['name']="cfg_templeturl";
$z[1]=Array("global","",463,492);
$z[1][4]['name']="cfg_templeturl";
$z[2]=Array("global","",577,606);
$z[2][4]['name']="cfg_templeturl";
$z[3]=Array("global","",679,708);
$z[3][4]['name']="cfg_templeturl";
$z[4]=Array("global","",757,786);
$z[4][4]['name']="cfg_templeturl";
$z[5]=Array("global","",910,939);
$z[5][4]['name']="cfg_templeturl";

?>